version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10
  cloudfoundry: circleci/cloudfoundry@<<pipeline.parameters.dev-orb-version>>
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  test_install:
    docker:
      - image: cimg/base:stable
    steps:
      - cloudfoundry/install
      - run: cf version

  test_install-nosudo:
    docker:
      - image: cimg/base:stable
    steps:
      - run: export SUDO_FORCE_REMOVE=yes; sudo -E apt purge sudo
      - cloudfoundry/install
      - run: cf version

  test_install-macos:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - cloudfoundry/install:
          platform: macosx
      - run: cf version

  test_deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Clone sample project
          command: git clone https://github.com/IBM-Cloud/get-started-go.git sample
      - run:
          name: Setup buildpack
          command: |
            echo \<<- EOF > sample/manifest.yml
            ---
            applications:
            - name: GetStartedGo
              random-route: true
              memory: 64M
              buildpacks: [go_buildpack]
            EOF
      - cloudfoundry/install
      - cloudfoundry/auth:
          endpoint: api.eu-gb.cf.cloud.ibm.com
          org: gabriel@circleci.com
          space: dev
      - cloudfoundry/push:
          appname: cpe-team-cloudfoundry-orb-testing
          manifest: sample/manifest.yml
          package: sample
          path: sample

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148,SC2001,SC1091,SC2086,SC2116,SC2046,SC2005,SC2002,SC1090
          shell: sh
      - orb-tools/pack:
          use-orb-pack: true
      - orb-tools/publish-dev:
          orb-name: circleci/cloudfoundry
          context: orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - shellcheck/check

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - test_install
      - test_install-macos
      - test_install-nosudo
      - test_deploy:
          context: cloudfoundry-orb-testing
          requires:
            - test_install
            - test_install-macos
            - test_install-nosudo
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/cloudfoundry
          context: orb-publishing
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: cpe-bot
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          filters:
            branches:
              only: master
          requires:
            - test_deploy
