version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10
  cloudfoundry: circleci/cloudfoundry@<<pipeline.parameters.dev-orb-version>>
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148,SC2001,SC1091,SC2086,SC2116,SC2046,SC2005,SC2002
          shell: sh
      - bats/run:
          path: ./tests
      - orb-tools/pack:
          use-orb-pack: true
      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      - orb-tools/publish-dev:
          orb-name: circleci/cloudfoundry
          context: orb-publishing
          requires:
            - hold-for-dev-publish

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/cloudfoundry
          context: orb-publishing
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: cpe-bot
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          filters:
            branches:
              only: master
